name: breakcheck

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  breakcheck:
    permissions: write-all

    strategy:
      matrix:
        go-version: [ 1.21.x ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Gorelease cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/bin/gorelease
          key: ${{ runner.os }}-gorelease

      - name: Generate gorelease report
        id: gorelease
        run: |
          test -e ~/go/bin/gorelease || go install golang.org/x/exp/cmd/gorelease@latest
          ls -la
          cd ${{ inputs.project }}
          ls -la
          echo "### Exported API Changes Report" >> ../gorelease.report
          echo "" >> ../gorelease.report
          echo "<pre>" >> ../gorelease.report
          gorelease
          echo "$(gorelease || exit 0)" >> ../gorelease.report
          echo "</pre>" >> ../gorelease.report
          cat ../gorelease.report

      - name: Comment Report on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: gorelease
          path: gorelease.report

      - name: Fail on API changes
        run: |
          if grep Incompatible gorelease.report ; then
            exit 1
          fi