name: breakcheck

on:
  pull_request:

env:
  GO111MODULE: "on"

jobs:
  breakcheck:
    permissions: write-all

    strategy:
      matrix:
        go-version: [ 1.21.x ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Gorelease cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/bin/gorelease
          key: ${{ runner.os }}-gorelease

      - name: Gorelease
        id: gorelease
        run: |
          test -e ~/go/bin/gorelease || go install golang.org/x/exp/cmd/gorelease@latest
          OUTPUT=$
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "report=$(gorelease || exit 0)" >> "$GITHUB_OUTPUT"
          
      - name: Comment Report on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: gorelease
          message: |
            ### Exported API Changes Report

            <pre>
            ${{ "${steps.gorelease.outputs.report//'%0A'/'\n'}" }}
            </pre>

      - name: Fail on API changes
        if : ${{ contains(steps.gorelease.outputs.report, 'Incompatible changes were detected') }}
        run: |
          if [[ -n "${{ steps.gorelease.outputs.report }}" ]] ; then
            echo "Incompatible changes were detected"
            exit 1
          fi